### ISSUE TITLE
cargo run have bug

### ISSUE THREAD

**Issue by trand2k** [evshary/zenoh_carla_bridge#17]
Hi author, 
i have this bug when run cargo run, help me fix this
![Screenshot from 2023-11-13 16-06-48](https://github.com/evshary/zenoh_carla_bridge/assets/53207542/41eef68e-e53c-4a69-8c3e-b886d8d132a9)

thank you.

**Comment by evshary** [comment]
Could you provide me with your system information?
Like the CPU architecture & Ubuntu version & the commit of zenoh_carla_bridge you use.
BTW, I would suggest to use [autoware_carla_launch](https://github.com/evshary/autoware_carla_launch) directly, since it puts everything in the container, which can avoid system environment issues.

**Comment by trand2k** [comment]
> Could you provide me with your system information? Like the CPU architecture & Ubuntu version & the commit of zenoh_carla_bridge you use. BTW, I would suggest to use [autoware_carla_launch](https://github.com/evshary/autoware_carla_launch) directly, since it puts everything in the container, which can avoid system environment issues.
I install on ubuntu 22.04, i already run ok autoware_carla_launch repo, it work, but i want to understand deeper, then i try to run each part

**Comment by evshary** [comment]
Since the bridge has some issues with building under Ubuntu 22.04, I think it would be better to use the container for your development.

You can run `./container/run-bridge-docker.sh` to enter the Ubuntu 20.04
https://github.com/evshary/autoware_carla_launch#carla-with-autoware

Then you can use a terminal multiplexer (like tmux) to split the terminal and then run the command here separately. 
https://github.com/evshary/autoware_carla_launch/blob/main/script/run-bridge.sh#L19

I think it's an easier way.

**Comment by trand2k** [comment]
> Since the bridge has some issues with building under Ubuntu 22.04, I think it would be better to use the container for your development.
> 
> You can run `./container/run-bridge-docker.sh` to enter the Ubuntu 20.04 https://github.com/evshary/autoware_carla_launch#carla-with-autoware
> 
> Then you can use a terminal multiplexer (like tmux) to split the terminal and then run the command here separately. https://github.com/evshary/autoware_carla_launch/blob/main/script/run-bridge.sh#L19
> 
> I think it's an easier way.

i will try this, thanks for your support

**Comment by trand2k** [comment]
> Since the bridge has some issues with building under Ubuntu 22.04, I think it would be better to use the container for your development.
> 
> You can run `./container/run-bridge-docker.sh` to enter the Ubuntu 20.04 https://github.com/evshary/autoware_carla_launch#carla-with-autoware
> 
> Then you can use a terminal multiplexer (like tmux) to split the terminal and then run the command here separately. https://github.com/evshary/autoware_carla_launch/blob/main/script/run-bridge.sh#L19
> 
> I think it's an easier way.

![Screenshot from 2023-11-14 14-50-30](https://github.com/evshary/zenoh_carla_bridge/assets/53207542/988164dd-7d00-4e6d-9b61-3242d710c4a2)
Hi author, 
In this part, Control topic is pub from autoware and Sensing topic and Output topic pub from carla, right ?

**Comment by evshary** [comment]
Input topic is from Autoware to bridge, while output topic is from bridge to Autoware

**Comment by evshary** [comment]
Since it's inactive for a while, let me close the issue.
Feel free to open if you have further questions.
